### ISSUE TITLE
Dependency name for fhir-cda

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/cda-ccda-2.2#10]
In ig.json I have:

```json
	"dependencyList": [{
		"name": "hl7.fhir.cda",
		"version": "0.0.1"
	}]
```
The IG Publisher is failing on this with the following error:
`Error : IG Name must be a valid token (hl7.fhir.cda)`

**Comment by seanmcilvenna** [comment]
I've also tried a number of other combinations of properties for the dependencyList...

```json
	"dependencyList": [{
		"name": "hl7fhircda",
		"package": "hl7.fhir.cda",
		"location": "https://build.fhir.org/ig/HL7/fhir-cda",
		"version": "0.0.1",
		"source": "dependencies/cda"
	}]
```
This is the last configuration I tried, and it is failing with
`Error : Error fetching package list for hl7.fhir.cda from http://hl7.org/fhir/cda/package-list.json: http://hl7.org/fhir/cda/package-list.json`

**Comment by rgeimer** [comment]
There is no package-list.json file at http://hl7.org/fhir/cda/package-list.json.
So that’s likely the issue now. Will need Grahame to push one there.

Rick

**Comment by grahamegrieve** [comment]
no you should make the version "current" for now - there's no released CDA version to depend on

**Comment by seanmcilvenna** [comment]
Using "current", I get an error:
`Error : Unable to resolve the package 'hl7.fhir.cda'`
