### ISSUE TITLE
Fix fhir-cda IG's publish from igpublisher

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/cda-ccda-2.2#5]
It is currently missing any framework/template/styles. Grahame says he intends to fix this. It is difficult in its current state to check it for issues, so this is a priority.

**Comment by grahamegrieve** [comment]
I'm on it. We want the CDA look, yes? I think I'm going to make a base CDA template

**Comment by seanmcilvenna** [comment]
Yes, a CDA look would be great. We should create a separate repository for the CDA template, so we can re-use the same thing in C-CDA, later.

**Comment by grahamegrieve** [comment]
I will work on the CDA template and we'll use that.
