### ISSUE TITLE
What should packageId be for CDA IGs?

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/cda-ccda-2.2#8]

**Comment by grahamegrieve** [comment]
we're talking about real CDA IGs, not CCDA on FHIR, right? 

hl7.cda.base.r2
hl7.cda.ccda

We should have a thread on zulip somewhere about whether to make the version part of the ccda package id. FHIR practice is not to do that in IGs, but we're going to do that in the base

**Comment by rgeimer** [comment]
I think we usually include realm too, right? So should be

hl7.cda.us.ccda

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by grahamegrieve** [comment]
yes indeed.
