### ISSUE TITLE
Debate over GitHub repository naming

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/cda-ccda-2.2#9]
There's some debate over what is the correct naming convention for CDA IGs/products in GitHub. We intend to move old artifacts over the GitHub for historical purposes, but we also are storing new CDA artifacts in GitHub already. Rather than having a "cda" repository for the old artifacts, and a "fhir-cda" repository for the new artifacts that use FHIR tooling, it was suggested that we just have a single "cda" repository for both, and separate them out with directory structures and/or branches for versioned artifacts/errata.

Another option that I was considering with @rgeimer today, was the possibility of having a separate "hl7-cda" account that is just for CDA stuff. This might be a good convention for the various products as a whole within HL7 (i.e. "hl7-fhir", "hl7-cda", "hl7-v2", etc.). I'm aware that creating a new account for "hl7-fhir" would mean moving a lot (all?) existing GitHub repositories to the other account, which would have a wide impact. But, we could start with CDA, since there's barely anything in GitHub for CDA, yet, and slowly transition FHIR stuff from "hl7" to "hl7-fhir".

**Comment by grahamegrieve** [comment]
TSC requirement to use HL7 organization. We should have a standard of starting all repos with xxx- where xxx is the product name e.g. fhir- or cda-. If we agree to this I can enforce it on the FHIR side.

We should rename the current fhir-cda to cda-base-fhir or something
